// eps_testcard.c
//
// The code in this file is part of PyXPlot
// <http://www.pyxplot.org.uk>
//
// Copyright (C) 2006-9 Dominic Ford <coders@pyxplot.org.uk>
//               2008-9 Ross Church
//
// $Id$
//
// PyXPlot is free software; you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation; either version 2 of the License, or (at your option) any later
// version.
//
// You should have received a copy of the GNU General Public License along with
// PyXPlot; if not, write to the Free Software Foundation, Inc., 51 Franklin
// Street, Fifth Floor, Boston, MA  02110-1301, USA

// ----------------------------------------------------------------------------

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "StringTools/asciidouble.h"
#include "StringTools/str_constants.h"

#include "ListTools/lt_list.h"
#include "ListTools/lt_memory.h"

#include "eps_hub.h"
#include "eps_latex.h"
#include "eps_testcard.h"

// error reporting routines

void output_log(char *msg)
 {
  static FILE *logfile = NULL;
  static int   latch = 0;
  char         linebuffer[LSTR_LENGTH];
  char         temp_logstring[LSTR_LENGTH];

  if (latch) return; // Do not allow recursive calls, which might be generated by the call to ppl_fatal below
  latch = 1;
  if (logfile==NULL)
   if ((logfile=fopen("testcard.log","w")) == NULL)
    output_fatal(__FILE__,__LINE__,"Could not open log file to write.");

  strcpy(temp_logstring, msg);
  fprintf(logfile, "[%s] %s\n", StrStrip(FriendlyTimestring(), linebuffer), temp_logstring);
  fflush(logfile);
  latch = 0;
  return;
 }

void output_fatal(char *file, int line, char *msg)
 {
  printf("Fatal Error encounted in %s at line %d:", file, line);
  printf("%s\n",msg);
  lt_FreeAll(0);
  if (DEBUG) output_log("Terminating with error condition 1.");
  exit(1);
 }

// main entry point

int main(int argc, char **argv)
 {
  List *StringList;

  // Initialise sub-modules
  if (DEBUG) output_log("Initialising Testcard Demo.");
  lt_MemoryInit(&output_fatal, &output_log);
  if (eps_HubInit(&output_fatal, &output_log) != 0) output_fatal(__FILE__,__LINE__,eps_ErrorString);

  // Make a list of LaTeX strings to render
  StringList = ListInit();
  ListAppendString(StringList, "plob");
  ListAppendString(StringList, "bolp");
  ListAppendString(StringList, "$i^2=-1$");

  // Render these strings
  if (eps_LaTeXProcess(StringList) != 0) output_fatal(__FILE__,__LINE__,eps_ErrorString);

  // Tidy up
  lt_FreeAll(0);
  lt_MemoryStop();
  if (DEBUG) output_log("Terminating normally.");
  return 0;
 }

